// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: earthquakes.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEarthquake = `-- name: CreateEarthquake :one
INSERT INTO public."earthquake" (
    magnitude, duration
) VALUES (
    $1, $2
)
RETURNING id, magnitude, duration, created_at
`

type CreateEarthquakeParams struct {
	Magnitude float64 `json:"magnitude"`
	Duration  int16   `json:"duration"`
}

func (q *Queries) CreateEarthquake(ctx context.Context, arg CreateEarthquakeParams) (Earthquake, error) {
	row := q.db.QueryRow(ctx, createEarthquake, arg.Magnitude, arg.Duration)
	var i Earthquake
	err := row.Scan(
		&i.ID,
		&i.Magnitude,
		&i.Duration,
		&i.CreatedAt,
	)
	return i, err
}

const getEarthquake = `-- name: GetEarthquake :one
SELECT id, magnitude, duration, created_at FROM public."earthquake"
WHERE id = $1
`

func (q *Queries) GetEarthquake(ctx context.Context, id pgtype.UUID) (Earthquake, error) {
	row := q.db.QueryRow(ctx, getEarthquake, id)
	var i Earthquake
	err := row.Scan(
		&i.ID,
		&i.Magnitude,
		&i.Duration,
		&i.CreatedAt,
	)
	return i, err
}

const listEarthquakes = `-- name: ListEarthquakes :many
SELECT id, magnitude, duration, created_at,
    CASE
        WHEN magnitude < 4.0 THEN 'minor'
        WHEN magnitude < 6.0 THEN 'moderate'
        WHEN magnitude < 8.0 THEN 'major'
        ELSE 'severe'
    END AS risk_level
FROM public."earthquake"
ORDER BY created_at ASC
`

type ListEarthquakesRow struct {
	ID        pgtype.UUID        `json:"id"`
	Magnitude float64            `json:"magnitude"`
	Duration  int16              `json:"duration"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	RiskLevel string             `json:"risk_level"`
}

func (q *Queries) ListEarthquakes(ctx context.Context) ([]ListEarthquakesRow, error) {
	rows, err := q.db.Query(ctx, listEarthquakes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEarthquakesRow
	for rows.Next() {
		var i ListEarthquakesRow
		if err := rows.Scan(
			&i.ID,
			&i.Magnitude,
			&i.Duration,
			&i.CreatedAt,
			&i.RiskLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEarthquakesByDateRange = `-- name: ListEarthquakesByDateRange :many
SELECT id, magnitude, duration, created_at FROM public."earthquake"
WHERE created_at >= $1 AND created_at <= $2
`

type ListEarthquakesByDateRangeParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

func (q *Queries) ListEarthquakesByDateRange(ctx context.Context, arg ListEarthquakesByDateRangeParams) ([]Earthquake, error) {
	rows, err := q.db.Query(ctx, listEarthquakesByDateRange, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Earthquake
	for rows.Next() {
		var i Earthquake
		if err := rows.Scan(
			&i.ID,
			&i.Magnitude,
			&i.Duration,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
