// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Earthquake struct {
	ID        pgtype.UUID        `json:"id"`
	Magnitude float64            `json:"magnitude"`
	Duration  int16              `json:"duration"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Reading struct {
	ID             pgtype.UUID        `json:"id"`
	SiAverage      float64            `json:"si_average"`
	SiMinimum      float64            `json:"si_minimum"`
	SiMaximum      float64            `json:"si_maximum"`
	Battery        float64            `json:"battery"`
	SignalStrength string             `json:"signal_strength"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID        string           `json:"id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	Token     string           `json:"token"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	IpAddress pgtype.Text      `json:"ip_address"`
	UserAgent pgtype.Text      `json:"user_agent"`
	UserID    pgtype.UUID      `json:"user_id"`
}

type Token struct {
	ID        pgtype.UUID        `json:"id"`
	Type      string             `json:"type"`
	Token     string             `json:"token"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID                  pgtype.UUID        `json:"id"`
	OauthID             string             `json:"oauth_id"`
	Name                string             `json:"name"`
	Email               string             `json:"email"`
	PhoneNumber         pgtype.Text        `json:"phone_number"`
	Role                string             `json:"role"`
	ProfileImage        string             `json:"profile_image"`
	IsInSchool          pgtype.Bool        `json:"is_in_school"`
	ExpoPushToken       pgtype.Text        `json:"expo_push_token"`
	WebPushSubscription []byte             `json:"web_push_subscription"`
	AlertNotification   bool               `json:"alert_notification"`
	PushNotification    bool               `json:"push_notification"`
	SmsNotification     bool               `json:"sms_notification"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}
