// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEarthquake(ctx context.Context, arg CreateEarthquakeParams) (Earthquake, error)
	CreateReading(ctx context.Context, arg CreateReadingParams) (Reading, error)
	CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetEarthquake(ctx context.Context, id pgtype.UUID) (Earthquake, error)
	GetFirstReadingDate(ctx context.Context) (pgtype.Timestamptz, error)
	GetLastReadingDate(ctx context.Context) (pgtype.Timestamptz, error)
	GetLatestBatteryLevel(ctx context.Context) (GetLatestBatteryLevelRow, error)
	GetReading(ctx context.Context, id pgtype.UUID) (Reading, error)
	GetToken(ctx context.Context, id pgtype.UUID) (Token, error)
	GetTokenByType(ctx context.Context, type_ string) (Token, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmailAndOAuthID(ctx context.Context, arg GetUserByEmailAndOAuthIDParams) (User, error)
	ListActivePushTokens(ctx context.Context) ([]ListActivePushTokensRow, error)
	ListAdminActivePushTokens(ctx context.Context) ([]ListAdminActivePushTokensRow, error)
	ListAlertNotificationEmails(ctx context.Context) ([]ListAlertNotificationEmailsRow, error)
	ListEarthquakes(ctx context.Context) ([]ListEarthquakesRow, error)
	ListEarthquakesByDateRange(ctx context.Context, arg ListEarthquakesByDateRangeParams) ([]Earthquake, error)
	ListReadings(ctx context.Context) ([]Reading, error)
	ListReadingsByDateRange(ctx context.Context, arg ListReadingsByDateRangeParams) ([]Reading, error)
	ListSMSPhoneNumbers(ctx context.Context) ([]string, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	RemoveUserPhoneNumber(ctx context.Context, id pgtype.UUID) (User, error)
	RemoveUserWebPushSubscription(ctx context.Context, id pgtype.UUID) (User, error)
	UpdateUserAlertNotification(ctx context.Context, arg UpdateUserAlertNotificationParams) (User, error)
	UpdateUserExpoPushToken(ctx context.Context, arg UpdateUserExpoPushTokenParams) (User, error)
	UpdateUserIsInSchool(ctx context.Context, arg UpdateUserIsInSchoolParams) (User, error)
	UpdateUserPhoneNumber(ctx context.Context, arg UpdateUserPhoneNumberParams) (User, error)
	UpdateUserPushNotification(ctx context.Context, arg UpdateUserPushNotificationParams) (User, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
	UpdateUserSMSNotification(ctx context.Context, arg UpdateUserSMSNotificationParams) (User, error)
	UpdateUserWebPushSubscription(ctx context.Context, arg UpdateUserWebPushSubscriptionParams) (User, error)
}

var _ Querier = (*Queries)(nil)
