// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuthContextByToken = `-- name: GetAuthContextByToken :one
SELECT
    s.id AS session_id,
    s.user_id,
    s.expires_at,
    u.role AS user_role
FROM session s
INNER JOIN "user" u ON u.id = s.user_id
WHERE s.token = $1 AND s.expires_at > now()
LIMIT 1
`

type GetAuthContextByTokenRow struct {
	SessionID string           `json:"session_id"`
	UserID    pgtype.UUID      `json:"user_id"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	UserRole  string           `json:"user_role"`
}

func (q *Queries) GetAuthContextByToken(ctx context.Context, token string) (GetAuthContextByTokenRow, error) {
	row := q.db.QueryRow(ctx, getAuthContextByToken, token)
	var i GetAuthContextByTokenRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.ExpiresAt,
		&i.UserRole,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, expires_at, token, created_at, updated_at, ip_address, user_agent, user_id FROM session
WHERE token = $1 AND expires_at > now()
LIMIT 1
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.ExpiresAt,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.UserID,
	)
	return i, err
}
