// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :one
INSERT INTO public."token" (
    token, type
) VALUES (
    $1, $2
)
RETURNING id, type, token, created_at, expires_at
`

type CreateTokenParams struct {
	Token string `json:"token"`
	Type  string `json:"type"`
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, createToken, arg.Token, arg.Type)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getToken = `-- name: GetToken :one
SELECT id, type, token, created_at, expires_at FROM public."token"
WHERE id = $1
`

func (q *Queries) GetToken(ctx context.Context, id pgtype.UUID) (Token, error) {
	row := q.db.QueryRow(ctx, getToken, id)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getTokenByType = `-- name: GetTokenByType :one
SELECT id, type, token, created_at, expires_at FROM public."token"
WHERE type = $1
`

func (q *Queries) GetTokenByType(ctx context.Context, type_ string) (Token, error) {
	row := q.db.QueryRow(ctx, getTokenByType, type_)
	var i Token
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
