// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pgtype$0 from "../../../../../github.com/jackc/pgx/v5/pgtype/models.js";

export interface ListEarthquakesRow {
    "id": pgtype$0.UUID;
    "magnitude": number;
    "duration": number;
    "created_at": pgtype$0.Timestamptz;
    "risk_level": string;
}

export interface ListUsersRow {
    "id": pgtype$0.UUID;
    "oauth_id": string;
    "name": string;
    "email": string;
    "phone_number": pgtype$0.Text;
    "role": string;
    "profile_image": string;
    "is_in_school": pgtype$0.Bool;
    "expo_push_token": pgtype$0.Text;
    "web_push_subscription": string | null;
    "alert_notification": boolean;
    "push_notification": boolean;
    "sms_notification": boolean;
    "created_at": pgtype$0.Timestamptz;
    "total_count": number;
}

export interface User {
    "id": pgtype$0.UUID;
    "oauth_id": string;
    "name": string;
    "email": string;
    "phone_number": pgtype$0.Text;
    "role": string;
    "profile_image": string;
    "is_in_school": pgtype$0.Bool;
    "expo_push_token": pgtype$0.Text;
    "web_push_subscription": string | null;
    "alert_notification": boolean;
    "push_notification": boolean;
    "sms_notification": boolean;
    "created_at": pgtype$0.Timestamptz;
}
