// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    Bool,
    Text,
    Timestamp,
    Timestamptz,
    UUID
} from "./models.js";
