// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type Bool = any;

export type Text = any;

/**
 * Timestamp represents the PostgreSQL timestamp type.
 */
export type Timestamp = any;

/**
 * Timestamptz represents the PostgreSQL timestamptz type.
 */
export type Timestamptz = any;

export type UUID = any;
