/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainEvacuationPlanRouteImport } from './routes/_main/evacuation-plan'
import { Route as MainProfileRouteImport } from './routes/_main/profile'
import { Route as MainProtocolsRouteImport } from './routes/_main/protocols'
import { Route as MainUserManagementRouteImport } from './routes/_main/user-management'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainEvacuationPlanRoute = MainEvacuationPlanRouteImport.update({
  id: '/evacuation-plan',
  path: '/evacuation-plan',
  getParentRoute: () => MainRoute,
} as any)
const MainProfileRoute = MainProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MainRoute,
} as any)
const MainProtocolsRoute = MainProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => MainRoute,
} as any)
const MainUserManagementRoute = MainUserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/error': typeof ErrorRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/evacuation-plan': typeof MainEvacuationPlanRoute
  '/profile': typeof MainProfileRoute
  '/protocols': typeof MainProtocolsRoute
  '/user-management': typeof MainUserManagementRoute
}
export interface FileRoutesByTo {
  '/error': typeof ErrorRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/evacuation-plan': typeof MainEvacuationPlanRoute
  '/profile': typeof MainProfileRoute
  '/protocols': typeof MainProtocolsRoute
  '/user-management': typeof MainUserManagementRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/error': typeof ErrorRoute
  '/privacy': typeof PrivacyRoute
  '/sign-in': typeof SignInRoute
  '/_main/evacuation-plan': typeof MainEvacuationPlanRoute
  '/_main/profile': typeof MainProfileRoute
  '/_main/protocols': typeof MainProtocolsRoute
  '/_main/user-management': typeof MainUserManagementRoute
  '/_main/': typeof MainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/privacy'
    | '/sign-in'
    | '/evacuation-plan'
    | '/profile'
    | '/protocols'
    | '/user-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/error'
    | '/privacy'
    | '/sign-in'
    | '/evacuation-plan'
    | '/profile'
    | '/protocols'
    | '/user-management'
    | '/'
  id:
    | '__root__'
    | '/_main'
    | '/error'
    | '/privacy'
    | '/sign-in'
    | '/_main/evacuation-plan'
    | '/_main/profile'
    | '/_main/protocols'
    | '/_main/user-management'
    | '/_main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  PrivacyRoute: typeof PrivacyRoute
  SignInRoute: typeof SignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/evacuation-plan': {
      id: '/_main/evacuation-plan'
      path: '/evacuation-plan'
      fullPath: '/evacuation-plan'
      preLoaderRoute: typeof MainEvacuationPlanRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/profile': {
      id: '/_main/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof MainProfileRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/protocols': {
      id: '/_main/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof MainProtocolsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/user-management': {
      id: '/_main/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof MainUserManagementRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainEvacuationPlanRoute: typeof MainEvacuationPlanRoute
  MainProfileRoute: typeof MainProfileRoute
  MainProtocolsRoute: typeof MainProtocolsRoute
  MainUserManagementRoute: typeof MainUserManagementRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainEvacuationPlanRoute: MainEvacuationPlanRoute,
  MainProfileRoute: MainProfileRoute,
  MainProtocolsRoute: MainProtocolsRoute,
  MainUserManagementRoute: MainUserManagementRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  ErrorRoute: ErrorRoute,
  PrivacyRoute: PrivacyRoute,
  SignInRoute: SignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
