/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as EvacuationPlanRouteImport } from './routes/evacuation-plan'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProtocolsRouteImport } from './routes/protocols'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as UserManagementRouteImport } from './routes/user-management'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const EvacuationPlanRoute = EvacuationPlanRouteImport.update({
  id: '/evacuation-plan',
  path: '/evacuation-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolsRoute = ProtocolsRouteImport.update({
  id: '/protocols',
  path: '/protocols',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementRoute = UserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/evacuation-plan': typeof EvacuationPlanRoute
  '/profile': typeof ProfileRoute
  '/protocols': typeof ProtocolsRoute
  '/sign-in': typeof SignInRoute
  '/user-management': typeof UserManagementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/evacuation-plan': typeof EvacuationPlanRoute
  '/profile': typeof ProfileRoute
  '/protocols': typeof ProtocolsRoute
  '/sign-in': typeof SignInRoute
  '/user-management': typeof UserManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/error': typeof ErrorRoute
  '/evacuation-plan': typeof EvacuationPlanRoute
  '/profile': typeof ProfileRoute
  '/protocols': typeof ProtocolsRoute
  '/sign-in': typeof SignInRoute
  '/user-management': typeof UserManagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/evacuation-plan'
    | '/profile'
    | '/protocols'
    | '/sign-in'
    | '/user-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error'
    | '/evacuation-plan'
    | '/profile'
    | '/protocols'
    | '/sign-in'
    | '/user-management'
  id:
    | '__root__'
    | '/'
    | '/error'
    | '/evacuation-plan'
    | '/profile'
    | '/protocols'
    | '/sign-in'
    | '/user-management'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErrorRoute: typeof ErrorRoute
  EvacuationPlanRoute: typeof EvacuationPlanRoute
  ProfileRoute: typeof ProfileRoute
  ProtocolsRoute: typeof ProtocolsRoute
  SignInRoute: typeof SignInRoute
  UserManagementRoute: typeof UserManagementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evacuation-plan': {
      id: '/evacuation-plan'
      path: '/evacuation-plan'
      fullPath: '/evacuation-plan'
      preLoaderRoute: typeof EvacuationPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocols': {
      id: '/protocols'
      path: '/protocols'
      fullPath: '/protocols'
      preLoaderRoute: typeof ProtocolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management': {
      id: '/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof UserManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErrorRoute: ErrorRoute,
  EvacuationPlanRoute: EvacuationPlanRoute,
  ProfileRoute: ProfileRoute,
  ProtocolsRoute: ProtocolsRoute,
  SignInRoute: SignInRoute,
  UserManagementRoute: UserManagementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
