// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ReadingItem {
    "id": string;
    "siAverage": number;
    "siMinimum": number;
    "siMaximum": number;
    "battery": number;
    "signalStrength": string;
    "createdAt": string;
    "riskLevel": string;
    "isSafe": boolean;
}

export interface ReadingsOverviewResult {
    "data": ReadingItem[] | null;
    "firstDate": string | null;
    "batteryLevel": number;
}
