// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as postgres$0 from "../adapters/postgresql/sqlc/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetReadingsOverview(startDate: string, endDate: string): $CancellablePromise<$models.ReadingsOverviewResult> {
    return $Call.ByID(3919665680, startDate, endDate);
}

export function ListEarthquakes(): $CancellablePromise<postgres$0.ListEarthquakesRow[] | null> {
    return $Call.ByID(3969331412);
}

export function SavePDFReport(filePath: string, base64Content: string): $CancellablePromise<void> {
    return $Call.ByID(2337579493, filePath, base64Content);
}
