// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as postgres$0 from "../adapters/postgresql/sqlc/models.js";

export interface ListUsersResult {
    "data": postgres$0.ListUsersRow[] | null;
    "pagination": Pagination;
}

export interface Pagination {
    "page": number;
    "pageSize": number;
    "total": number;
    "totalPages": number;
    "hasNextPage": boolean;
    "hasPreviousPage": boolean;
}
