// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as postgres$0 from "../adapters/postgresql/sqlc/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function DeleteUser(id: string): $CancellablePromise<postgres$0.User> {
    return $Call.ByID(4156616746, id);
}

export function GetUser(id: string): $CancellablePromise<postgres$0.User> {
    return $Call.ByID(16926945, id);
}

export function ListUsers(name: string, page: number, pageSize: number): $CancellablePromise<$models.ListUsersResult> {
    return $Call.ByID(1996698694, name, page, pageSize);
}

export function RemoveUserPhoneNumber(id: string): $CancellablePromise<postgres$0.User> {
    return $Call.ByID(4191500978, id);
}

export function UpdateUserAlertNotification(id: string, enabled: boolean): $CancellablePromise<postgres$0.User> {
    return $Call.ByID(3547939389, id, enabled);
}

export function UpdateUserPhoneNumber(id: string, phone: string): $CancellablePromise<postgres$0.User> {
    return $Call.ByID(2899866661, id, phone);
}

export function UpdateUserRole(id: string, role: string): $CancellablePromise<postgres$0.User> {
    return $Call.ByID(477441544, id, role);
}

export function UpdateUserSMSNotification(id: string, enabled: boolean): $CancellablePromise<postgres$0.User> {
    return $Call.ByID(3171738982, id, enabled);
}
